/usr/bin/python2.7 /home/achry/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras --bag /media/achry/LENOVO_USB_HDD/temp/field20211205/calib/output_calib.bag --topics /cam0/image_raw /cam1/image_raw --models pinhole-radtan pinhole-radtan --target /home/achry/CalibrData/april_6x6.yaml
importing libraries
Initializing cam0:
	Camera model:	  pinhole-radtan
	Dataset:          /media/achry/LENOVO_USB_HDD/temp/field20211205/calib/output_calib.bag
	Topic:            /cam0/image_raw
	Number of images: 44
Extracting calibration target corners
  Progress 3 / 44 	 Time remaining: 31m 56s                 Traceback (most recent call last):
  File "/home/achry/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 451, in <module>
    main()
  File "/home/achry/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 178, in main
    noTransformation=True)
  File "/home/achry/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 76, in extractCornersFromDataset
    raise RuntimeError("Exception during multithreaded extraction: {0}".format(e))
RuntimeError: Exception during multithreaded extraction: [Errno 32] Broken pipe
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/achry/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 17, in multicoreExtractionWrapper
    task = taskq.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

进程已结束,退出代码1
